export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: {

      venues: {
        Row: {
          id: string;
          name: string;
          name_hy: string | null;
          name_ru: string | null;
          name_en: string | null;
          cuisine: string;
          cuisine_hy: string | null;
          cuisine_ru: string | null;
          cuisine_en: string | null;
          area: string;
          area_hy: string | null;
          area_ru: string | null;
          area_en: string | null;
          price: string;
          rating: number;
          reviews_count: number;
          photo_url: string;
          dish_url: string;
          distance_km: string;
          booked_today: number;
          heat: 'high' | 'med' | 'low';
          kind: 'restaurant' | 'bar' | 'lounge' | 'club';
          coord_x: number;
          coord_y: number;
          description: string;
          description_hy: string | null;
          description_ru: string | null;
          description_en: string | null;
          times: string[];
          perk: string;
          perk_hy: string | null;
          perk_ru: string | null;
          perk_en: string | null;
          tags: string[];
          tags_hy: string[] | null;
          tags_ru: string[] | null;
          tags_en: string[] | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          name_hy?: string | null;
          name_ru?: string | null;
          name_en?: string | null;
          cuisine: string;
          cuisine_hy?: string | null;
          cuisine_ru?: string | null;
          cuisine_en?: string | null;
          area: string;
          area_hy?: string | null;
          area_ru?: string | null;
          area_en?: string | null;
          price: string;
          rating: number;
          reviews_count: number;
          photo_url: string;
          dish_url: string;
          distance_km: string;
          booked_today: number;
          heat: 'high' | 'med' | 'low';
          kind: 'restaurant' | 'bar' | 'lounge' | 'club';
          coord_x: number;
          coord_y: number;
          description: string;
          description_hy?: string | null;
          description_ru?: string | null;
          description_en?: string | null;
          times: string[];
          perk: string;
          perk_hy?: string | null;
          perk_ru?: string | null;
          perk_en?: string | null;
          tags: string[];
          tags_hy?: string[] | null;
          tags_ru?: string[] | null;
          tags_en?: string[] | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['venues']['Insert']>;
        Relationships: [];
      };

      reservations: {
        Row: {
          id: string;
          user_id: string;
          venue_id: string;
          people: number;
          date: string;
          date_iso: string | null;
          time: string;
          occasion: string | null;
          note: string | null;
          status: 'pending' | 'confirmed' | 'cancelled' | 'visited';
          yel_earned: string;
          admin_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          venue_id: string;
          people: number;
          date: string;
          date_iso?: string | null;
          time: string;
          occasion?: string | null;
          note?: string | null;
          status: 'pending' | 'confirmed' | 'cancelled' | 'visited';
          yel_earned: string;
          admin_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          venue_id?: string;
          people?: number;
          date?: string;
          date_iso?: string | null;
          time?: string;
          occasion?: string | null;
          note?: string | null;
          status?: 'pending' | 'confirmed' | 'cancelled' | 'visited';
          yel_earned?: string;
          admin_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      favorites: {
        Row: {
          id: string;
          user_id: string;
          venue_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          venue_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          venue_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      profiles: {
        Row: {
          id: string;
          name: string;
          email: string;
          avatar_url: string | null;
          tier: string;
          tier_level: number;
          yel_points: number;
          total_visits: number;
          is_admin: boolean;
          role: 'user' | 'admin' | 'super_admin';
          managed_venue_id: string | null;
          managed_venue_ids: string[];
          push_token: string | null;
          web_push_sub: Record<string, unknown> | null;
          player_id: number;
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          avatar_url?: string | null;
          tier?: string;
          tier_level?: number;
          yel_points?: number;
          total_visits?: number;
          is_admin?: boolean;
          role?: 'user' | 'admin' | 'super_admin';
          managed_venue_id?: string | null;
          managed_venue_ids?: string[];
          push_token?: string | null;
          web_push_sub?: Record<string, unknown> | null;
          player_id?: number;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          avatar_url?: string | null;
          tier?: string;
          tier_level?: number;
          yel_points?: number;
          total_visits?: number;
          is_admin?: boolean;
          role?: 'user' | 'admin' | 'super_admin';
          managed_venue_id?: string | null;
          managed_venue_ids?: string[];
          push_token?: string | null;
          web_push_sub?: Record<string, unknown> | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      menu_categories: {
        Row: {
          id: string;
          venue_id: string;
          name: string;
          name_hy: string | null;
          name_ru: string | null;
          name_en: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          venue_id: string;
          name: string;
          name_hy?: string | null;
          name_ru?: string | null;
          name_en?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          venue_id?: string;
          name?: string;
          name_hy?: string | null;
          name_ru?: string | null;
          name_en?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      menu_items: {
        Row: {
          id: string;
          venue_id: string;
          category_id: string;
          name: string;
          name_hy: string | null;
          name_ru: string | null;
          name_en: string | null;
          description: string | null;
          description_hy: string | null;
          description_ru: string | null;
          description_en: string | null;
          price: number;
          photo_url: string | null;
          is_available: boolean;
          is_popular: boolean;
          allergens: string[];
          allergens_hy: string[] | null;
          allergens_ru: string[] | null;
          allergens_en: string[] | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          venue_id: string;
          category_id: string;
          name: string;
          name_hy?: string | null;
          name_ru?: string | null;
          name_en?: string | null;
          description?: string | null;
          description_hy?: string | null;
          description_ru?: string | null;
          description_en?: string | null;
          price: number;
          photo_url?: string | null;
          is_available?: boolean;
          is_popular?: boolean;
          allergens?: string[];
          allergens_hy?: string[] | null;
          allergens_ru?: string[] | null;
          allergens_en?: string[] | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          venue_id?: string;
          category_id?: string;
          name?: string;
          name_hy?: string | null;
          name_ru?: string | null;
          name_en?: string | null;
          description?: string | null;
          description_hy?: string | null;
          description_ru?: string | null;
          description_en?: string | null;
          price?: number;
          photo_url?: string | null;
          is_available?: boolean;
          is_popular?: boolean;
          allergens?: string[];
          allergens_hy?: string[] | null;
          allergens_ru?: string[] | null;
          allergens_en?: string[] | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      guides: {
        Row: {
          id: string;
          title: string;
          title_hy: string | null;
          title_ru: string | null;
          title_en: string | null;
          subtitle: string;
          subtitle_hy: string | null;
          subtitle_ru: string | null;
          subtitle_en: string | null;
          count: number;
          cover_url: string;
          tag: string;
          tag_hy: string | null;
          tag_ru: string | null;
          tag_en: string | null;
          sort_order: number;
          is_active: boolean;
          venue_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          title: string;
          title_hy?: string | null;
          title_ru?: string | null;
          title_en?: string | null;
          subtitle: string;
          subtitle_hy?: string | null;
          subtitle_ru?: string | null;
          subtitle_en?: string | null;
          count?: number;
          cover_url: string;
          tag: string;
          tag_hy?: string | null;
          tag_ru?: string | null;
          tag_en?: string | null;
          sort_order?: number;
          is_active?: boolean;
          venue_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          title_hy?: string | null;
          title_ru?: string | null;
          title_en?: string | null;
          subtitle?: string;
          subtitle_hy?: string | null;
          subtitle_ru?: string | null;
          subtitle_en?: string | null;
          count?: number;
          cover_url?: string;
          tag?: string;
          tag_hy?: string | null;
          tag_ru?: string | null;
          tag_en?: string | null;
          sort_order?: number;
          is_active?: boolean;
          venue_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

export type VenueRow        = Database['public']['Tables']['venues']['Row'];
export type ReservationRow  = Database['public']['Tables']['reservations']['Row'];
export type FavoriteRow     = Database['public']['Tables']['favorites']['Row'];
export type ProfileRow      = Database['public']['Tables']['profiles']['Row'];
export type MenuCategoryRow = Database['public']['Tables']['menu_categories']['Row'];
export type MenuItemRow     = Database['public']['Tables']['menu_items']['Row'];
export type GuideRow        = Database['public']['Tables']['guides']['Row'];
